##
## Makefile for Makefile in /home/bougon_p/rendu/TEK2/cpp_arcade/lib/sfml
## 
## Made by bougon_p
## Login   <bougon_p@epitech.net>
## 
## Started on  Sun Apr  2 00:32:42 2017 bougon_p
## Last update Sun Apr  2 00:42:29 2017 bougon_p
##

## Include colors and basic commands

include ../mk/colors.mk ../mk/commands.mk ../mk/definitions.mk

## Lib variab
SRC	=	src/SFMLCore.cpp	\
		src/GfxSprite.cpp	

OBJ 	=   	$(SRC:.cpp=.o)

NAME    =      	lib_arcade_sfml.so

INC     =       -Iinclude -I../../ArcadeInterfaces

## Lib rules

include ../mk/rules.mk