##
## Makefile for Makefile in /home/bougon_p/rendu/TEK2/cpp_arcade/core
## 
## Made by bougon_p
## Login   <bougon_p@epitech.net>
## 
## Started on  Sat Apr  1 13:38:06 2017 bougon_p
## Last update Sat Apr  1 17:30:04 2017 bougon_p
##

## Include colors and basic commands

include ../mk/colors.mk ../mk/commands.mk ../mk/definitions.mk

## Core variables

SRC	=	src/Core.cpp	\
		src/Factory.cpp	\
		src/Gui.cpp	\
		src/Pars.cpp	\
		src/Text.cpp

OBJ 	=   	$(SRC:.cpp=.o)

NAME    =      	../arcade

INC     =       -Iinclude -I../interfaces

## Core rules

include ../mk/rules.mk
